name: chat_with_bloc
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  adaptive_dialog: ^2.2.1+2
  flutter_native_image: ^0.0.6+1
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  cloud_firestore: ^5.4.5
  firebase_storage: ^12.3.5
  change_app_package_name: ^1.3.0
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  audio_waveforms: ^1.1.1
  flutter_cache_manager: ^3.4.1
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.5
  video_player: ^2.9.2
  chewie: ^1.7.5
  geolocator: ^10.0.1
  geocoding: ^3.0.0
  # geoflutterfire2: ^2.3.15
  google_maps_flutter: ^2.9.0
  flutter_svg: ^2.0.14
  date_picker_plus: ^4.1.0
  syncfusion_flutter_core: ^27.1.58
  syncfusion_flutter_sliders: ^27.1.58
  flutter_webrtc: ^0.12.1+hotfix.1
  # web_socket_channel: ^3.0.1
  flutter_background: ^1.3.0+1
  image_gallery_saver: ^2.0.3
  http: ^1.2.2
  hive: ^2.2.3
  url_launcher: ^6.3.1
  timeago: ^3.7.0
  google_sign_in: ^6.2.2
  country_code_picker: ^3.1.0
  pinput: ^5.0.0
  sign_in_with_apple: ^6.1.3
  story_view: ^0.16.5
  google_maps_place_picker_mb: ^3.1.2
  flutter_localizations:
    sdk: flutter
  intl_utils: ^2.8.7
  get_storage: ^2.1.1
  flutter_dotenv: ^5.2.1
  flutter_stripe: ^11.2.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/png/
    - assets/images/svg/
  
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
